name: IAC Scan
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  inspec_check:
    runs-on: ubuntu-latest
    steps:
      - run : curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
      - name: Run Inspec  
        run: id=$( docker run -dti ubuntu:14.04 /bin/bash ) | inspec detect -t docker://$id
        #run: inspec exec test.rb --reporter=json:/inspec-output/inspec_results.json
      - name: Upload Inspec Results
        uses: actions/upload-artifact@v2
        with:
          name: inspec_results
          path: /inspec-output/inspec_results.json

  inspec_tools_compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code for Threshold
        uses: actions/checkout@v2
      - name: Download Inspec Results
        uses: actions/download-artifact@v2
        with:
          name: inspec_results
      - name: Inspec Tools Check Compliance
        uses: mitre/inspec_tools_action@main
        with:
          command: compliance
          resultfile: inspec_results.json
          thresholdfile: threshold.yaml
