name: Kics Infrastructure as Code Security Scan

on:
  push:
  workflow_dispatch:
  
jobs:
  Kicks-iac-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job...
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: mkdir -p myResults
      # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-github-action@v1.4
      with:
        # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
        path: 'terraform/aws/main.tf'
        output_path: myResults/
        output_formats: sarif
        ignore_on_exit: results
    # Display the results in json format
    - name: display kics results
      run: |
        cat myResults/results.json
