name: Example workflow for Snyk Infrastructure as Code
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p myResults
      - name: Run Snyk to scan the repo files for issues
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.Snyk_Token }}
          output_path: myResults/
          output_formats: sarif
          ignore_on_exit: results
          
      - name: Archive Scan results
        uses: actions/upload-artifact@v2
        with:
          name: scan-report
          path: myResults/results.sarif
     
